<?php $this->layout()->setVariable('titulo', 'Principal'); ?>


<div class="box box-primary">
    <!--<div class="box-header">
        <h3 class="box-title"></h3>
    </div>--><!-- /.box-header -->
    <div class="box-body">
        <div class="row">
            <div class="col-lg-6">

                <ul class="nav nav-pills nav-stacked">
                    <li class="">
                        <a href="#">Receita
                            <span class="pull-right text-green">R$ 2000</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">Despesa
                            <span class="pull-right text-red"> R$120</span>
                        </a>
                    </li>

                </ul>
            </div>
            <div class="col-lg-6">
                <div class="row">
                    <div class="col-lg-4 col-xs-6">
                        <div class="small-box bg-red">
                            <div class="inner">
                                <h3 class="text-center" style="margin: 0;">
                                    <i class="fa fa-plus"></i>
                                </h3>
                                <div class="text-center">Despesa</div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-xs-6">
                        <div class="small-box bg-green">
                            <div class="inner">
                                <h3 class="text-center" style="margin: 0;">
                                    <i class="fa fa-plus"></i>
                                </h3>
                                <div class="text-center">Receita</div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-xs-6">
                        <div class="small-box bg-blue">
                            <div class="inner">
                                <h3 class="text-center" style="margin: 0;">
                                    <i class="fa fa-plus"></i>
                                </h3>
                                <div class="text-center">Transferir</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
        <div class="row">

            
        </div>
</div>

