<?php
/** @var  $element Zend\Form\Element\Text*/
$element = $this->element;


?>
<div class="form-group <?php if($this->formElementErrors($element)) echo " has-error" ?>">
    <label><?php echo $element->getLabel();?></label>
    <textarea class="form-control"  rows="<?php echo $element->getAttribute('rows');?>"  cols="<?php echo $element->getAttribute('cols');?>" placeholder="<?php echo $element->getAttribute('placeholder');?>" name="<?php echo $element->getAttribute('name');?>" ><?php echo $element->getValue()?></textarea>
</div>