<?php
/** @var  $element Zend\Form\Element\File*/
$element = $this->element;
?>

<div class="form-group <?php if($this->formElementErrors($element)) echo " has-error" ?>">
    <label for="<?php echo $element->getAttribute('id');?>">
        <?php echo $element->getLabel();?>
    </label>
    <input type="file" id="<?php echo $element->getAttribute('id');?>" name="<?php echo $element->getName(); ?>" value="<?php echo $element->getValue()?>">
    <p class="help-block"><?php echo $element->getAttribute('help-block');?></p>
</div>


