<?php
/** @var  $row \Application\Entity\Transferencia*/
$data = $this->data;
$this->layout()->setVariable('titulo', 'Transferências');
?>


<div class="row" style="margin-top: -35px; margin-bottom: 10px;">
    <div class="col-lg-12">
        <a href="<?php echo $this->url('transferencia/default', array('action'=>'cadastrar',)); ?>" class="btn btn-primary pull-right">
            <i class="fa fa-plus"></i>
            Transferir
        </a>
    </div>
</div>

<div class="box">
    <!--<div class="box-header with-border">
    </div>-->
    <div class="box-body">
        <?php echo $this->partial('partial/messages');?>
        <table  class="table table-bordered table-striped" id="table-search-columns">
            <thead>
            <tr>
                <th style="vertical-align:middle">Origem</th>
                <th style="vertical-align:middle">Destino</th>
                <th style="vertical-align:middle">Valor</th>
            </tr>
            </thead>

            <tbody>
            <?php foreach($data as $row): ?>
                <tr>
                    <td style="vertical-align:middle"><?php echo $row->getOrigem()->getNome(); ?></td>
                    <td style="vertical-align:middle"><?php echo $row->getDestino()->getNome(); ?></td>
                    <td style="vertical-align:middle"><?php echo $this->currencyFormat($row->getValor(), 'BRL', true, 'pt_BR', 'R$ #0.#'); ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div><!-- /.box-body -->
</div><!-- /.box -->