<?php
/** @var $this \Zend\View\Renderer\PhpRenderer */
/** @var  $usuario \Application\Entity\Usuario Usuario logado */
/** @var  $contador \Application\Entity\Contador Contador logado*/
/** @var  $cliente  Application\Entity\Cliente Clientes que são gerenciados pelocontador logado*/
/** @var  $cliente_selecionado  Application\Entity\Cliente*/

$container  = new \Zend\Session\Container('logado');
$usuario    = $container->offsetGet('usuario');
$cliente = $usuario['cliente'];

?>

    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <!--<div class="user-panel">
                <div class="pull-left image">
                    <img src="../../dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                </div>-
                <div class="pull-left info">
                    <p>Joabe Pinheiro</p>
                    <a href="#">Contador</a>
                </div>
            </div>->
            <!-- search form -->

            <ul class="sidebar-menu">

                    <!-- /.search form -->
                    <!-- sidebar menu: : style can be found in sidebar.less -->

                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-barcode"></i> <span>NF-e</span> <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="<?php echo $this->url('nfe/default', array(
                                    'action' => 'enviar'
                                ))?>"><i class="fa fa-send"></i> Enviar notas</a></li>
                            <li><a href="<?php echo $this->url('nfe/default', array(
                                    'action' => 'listar'
                                ))?>"><i class="fa fa-list"></i> listar</a></li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-life-ring" aria-hidden="true"></i> <span>Suporte</span> <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="<?php echo $this->url('suporte/default', array(
                                    'action' => 'contato'
                                ))?>"><i class="fa fa-envelope-o" aria-hidden="true"></i> Contato</a></li>
                            <li><a href="<?php echo $this->url('suporte/default', array(
                                    'action' => 'faq'
                                ))?>"><i class="fa fa-question" aria-hidden="true"></i> FAQ</a></li>
                        </ul>
                    </li>


            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>




<?php $this->headScript()->captureStart() ?>
    $(document).ready(function () {

    $("#selecionar-cliente").change(function () {
    var stateId = $(this).val();
    if(stateId !== "") {
    // you might want to change this
    var url = "/contador/selecionar-cliente/"+stateId;
    $.getJSON( url, function( data ) {
    location.reload();
    });
    }
    });

    });
<?php $this->headScript()->captureEnd() ?>