<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <!--<div class="user-panel">
            <div class="pull-left image">
                <img src="../../dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
            </div>-
            <div class="pull-left info">
                <p>Joabe Pinheiro</p>
                <a href="#">Contador</a>
            </div>
        </div>->
        <!-- search form -->
        <!-- <form action="#" method="get" class="sidebar-form">
             <div class="input-group">
                 <input type="text" name="q" class="form-control" placeholder="Search...">
               <span class="input-group-btn">
                 <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
               </span>
             </div>
         </form>-->
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <!-- <li class="header">MAIN NAVIGATION</li>-->

            <li class="treeview">
                <a href="#">
                    <i class="fa fa-file-text"></i> <span>Anexo 1</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="<?php echo $this->url('anexo/default', array('action' => 'cadastrar'))?>"><i class="fa fa-plus"></i> Cadastrar</a></li>
                    <li><a href="<?php echo $this->url('anexo/default', array('action' => 'listar'))?>"><i class="fa fa-list"></i> Listar</a></li>
                </ul>
            </li>

            <li class="treeview">
                <a href="#">
                    <i class="fa fa-file-text"></i> <span>Protocolos</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="<?php echo $this->url('protocolo/default', array('action' => 'cadastrar'))?>"><i class="fa fa-plus"></i> Cadastrar</a></li>
                    <li><a href="<?php echo $this->url('protocolo/default', array('action' => 'listar'))?>"><i class="fa fa-list"></i> Listar</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-table"></i> <span>ICMS</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="<?php echo $this->url('icms/default', array('action' => 'cadastrar'))?>"><i class="fa fa-plus"></i> Cadastrar</a></li>
                    <li><a href="<?php echo $this->url('icms/default', array('action' => 'listar'))?>"><i class="fa fa-list"></i> Listar</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-user"></i> <span>Contador</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="<?php echo $this->url('contador/default', array('action' => 'cadastrar'))?>"><i class="fa fa-plus"></i> Cadastrar</a></li>
                    <li><a href="<?php echo $this->url('contador/default', array('action' => 'listar'))?>"><i class="fa fa-list"></i> Listar</a></li>
                </ul>
            </li>


            <li class="header">CONTROLE DE ACESSO</li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-key"></i> <span>Privilégios</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="<?php echo $this->url('acl-privileges/default', array('action' => 'cadastrar'))?>"><i class="fa fa-plus"></i> Cadastrar</a></li>
                    <li><a href="<?php echo $this->url('acl-privileges/default', array('action' => 'listar'))?>"><i class="fa fa-list"></i> Listar</a></li>
                </ul>
            </li>

            <li class="treeview">
                <a href="#">
                    <i class="fa fa-lock"></i> <span>Recursos</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="<?php echo $this->url('acl-resources/default', array('action' => 'cadastrar'))?>"><i class="fa fa-plus"></i> Cadastrar</a></li>
                    <li><a href="<?php echo $this->url('acl-resources/default', array('action' => 'listar'))?>"><i class="fa fa-list"></i> Listar</a></li>
                </ul>
            </li>


            <li class="treeview">
                <a href="#">
                    <i class="fa fa-user"></i> <span>Papeis</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="<?php echo $this->url('acl-roles/default', array('action' => 'cadastrar'))?>"><i class="fa fa-plus"></i> Cadastrar</a></li>
                    <li><a href="<?php echo $this->url('acl-roles/default', array('action' => 'listar'))?>"><i class="fa fa-list"></i> Listar</a></li>
                </ul>
            </li>
        </ul>




    </section>
    <!-- /.sidebar -->
</aside>