<?php
/** @var  $row \Application\Entity\Despesa*/
$data = $this->data;
$this->layout()->setVariable('titulo', 'Despesas');
?>

<div class="row" style="margin-top: -35px; margin-bottom: 10px;">
    <div class="col-lg-12">
        <a href="<?php echo $this->url('despesa/default', array('action'=>'cadastrar',)); ?>" class="btn btn-primary pull-right">
            <i class="fa fa-plus"></i>
            Nova receita
        </a>
    </div>
</div>

<div class="box">
    <!--<div class="box-header with-border">
    </div>-->
    <div class="box-body">
        <?php echo $this->partial('partial/messages');?>
        <table  class="table table-bordered table-striped" id="table-search-columns">
            <thead>
            <tr>
                <th style="vertical-align:middle">Efetuada</th>
                <th style="vertical-align:middle">Descrição</th>
                <th style="vertical-align:middle">Valor</th>
                <th style="vertical-align:middle">Conta</th>
                <th style="vertical-align:middle">Categoria</th>
                <th style="vertical-align:middle">Data</th>
                <th style="vertical-align:middle">Recibo</th>
                <th style="vertical-align:middle"></th>
                <th style="vertical-align:middle"></th>
            </tr>
            </thead>

            <tbody>
            <?php foreach($data as $row): ?>
                <tr>
                    <td style="vertical-align:middle">
                        <?php if($row->isEfetuada()):?>
                            <i class="fa fa-check text-success"></i>
                        <?php else:?>
                            <i class="fa fa-check text-danger"></i>
                        <?php endif ?>
                    </td>
                    <td style="vertical-align:middle"><?php echo $row->getDescricao(); ?></td>
                    <td style="vertical-align:middle"><?php echo $row->getValor(); ?></td>
                    <td style="vertical-align:middle"><?php echo $row->getConta()->getNome(); ?></td>
                    <td style="vertical-align:middle"><?php echo $row->getCategoria()->getNome(); ?></td>
                    <td style="vertical-align:middle"><?php echo $row->getData(); ?></td>
                    <td style="vertical-align:middle">
                        <a href="<?php echo $this->url('despesa/default', array('action'=>'gerar-recibo', 'id' => $row->getId(),)); ?>">
                            <i class="fa fa-ticket"></i>
                        </a>
                    </td>
                    <td style="vertical-align:middle">
                        <a href="<?php echo $this->url('despesa/default', array('action'=>'editar', 'id' => $row->getId(),)); ?>">
                            <i class="fa fa-edit"></i>
                        </a>
                    </td>
                    <td style="vertical-align:middle">
                        <a href="<?php echo $this->url('despesa/default', array('action'=>'deletar', 'id' => $row->getId(),)); ?>">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div><!-- /.box-body -->
</div><!-- /.box -->