<?php
/** @var  $row \Application\Entity\Consultor */
$data = $this->data;
$this->layout()->setVariable('titulo', 'Consultores');
?>


<div class="row" style="margin-top: -35px; margin-bottom: 10px;">
    <div class="col-lg-12">
        <a href="<?php echo $this->url('consultor/default', array('action'=>'cadastrar',)); ?>" class="btn btn-primary pull-right">
            <i class="fa fa-plus"></i>
            Novo consultor
        </a>
    </div>
</div>

<div class="box">
    <!--<div class="box-header with-border">
    </div>-->
    <div class="box-body">
        <?php echo $this->partial('partial/messages');?>
        <table  class="table table-bordered table-striped" id="table-search-columns">
            <thead>
                <tr>
                    <th style="vertical-align:middle">Nome</th>
                    <th style="vertical-align:middle">Email</th>
                    <th style="vertical-align:middle">Cadastrado em</th>
                    <th style="vertical-align:middle">Editar</th>
                    <th style="vertical-align:middle">Status</th>
                </tr>
            </thead>

            <tbody>
            <?php foreach($data as $row): ?>
                <tr>
                    <td style="vertical-align:middle"><?php echo $row->getUsuario()->getNome(); ?></td>
                    <td style="vertical-align:middle"><?php echo $row->getUsuario()->getEmail(); ?></td>
                    <td style="vertical-align:middle"><?php echo $row->getUsuario()->getCadastradoEm()->format('d/m/y H:i'); ?></td>
                    <td style="vertical-align:middle">
                        <a href="<?php echo $this->url('consultor/default', array('action'=>'editar', 'id' => $row->getId(),)); ?>">
                            <i class="fa fa-edit"></i>
                        </a>
                    </td>
                    <td>
                        <?php if($row->getUsuario()->isAtivo()):?>
                            <a href="<?php echo $this->url('consultor/default', array('action'=>'editar', 'id' => $row->getId(),)); ?>" title="Ativo">
                                <span class="label label-success button-crud">
                                    <i class="fa fa-unlock"></i>
                                </span>
                            </a>
                        <?php else: ?>
                            <a href="<?php echo $this->url('consultor/default', array('action'=>'editar', 'id' => $row->getId(),)); ?>" title="Inativo">
                                <span class="label label-danger button-crud">
                                    <i class="fa fa-lock"></i>
                                </span>
                            </a>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div><!-- /.box-body -->
</div><!-- /.box -->