<?php
/** @var $this \Zend\View\Renderer\PhpRenderer */
/** @var  $usuario \Application\Entity\Usuario Usuario logado */
/** @var  $contador \Application\Entity\Contador Contador logado*/
/** @var  $cliente  Application\Entity\Cliente Clientes que são gerenciados pelocontador logado*/
/** @var  $cliente_selecionado  Application\Entity\Cliente*/

$container  = new \Zend\Session\Container('logado');
$usuario    = $container->offsetGet('usuario');
$contador = $usuario['contador'];
$clientes = $container->offsetGet('clientes');
$cliente_selecionado = $container->offsetGet('cliente-selecionado');

$id_cliente_selecionado = (is_null($container->offsetGet('cliente-selecionado')) ? 0 : $cliente_selecionado['id']);

?>

<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <!--
        <div class="user-panel">
            <div class="pull-left image">
                <img src="<?php echo $cliente_selecionado['perfil']; ?>" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p><?php echo substr($cliente_selecionado['nome_fantasia'], 0 , 20);?></p>
            </div>
        </div>
        -->
        <!-- search form -->
         <form action="#" method="get" class="sidebar-form">
                 <select  class="form-control" id="selecionar-cliente" onchange="carregando()">
                     <option value="0">Selecione um cliente</option>
                     <?php foreach($clientes as $cliente):?>
                         <option <?php echo ($id_cliente_selecionado == $cliente->getId()) ? 'selected' : ''?> value="<?php echo $cliente->getId();?>"><?php echo $cliente->getNomeFantasia(); ?></option>
                     <?php endforeach; ?>
                 </select>
         </form>

        <ul class="sidebar-menu">
        <?php if(!is_null($cliente_selecionado)):?>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->

            <li class="treeview">
                <a href="#">
                    <i class="fa fa-barcode"></i> <span>NF-e</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="<?php echo $this->url('nfe/default', array(
                            'action' => 'enviar'
                        ))?>"><i class="fa fa-send"></i> Enviar notas</a></li>
                    <li><a href="<?php echo $this->url('nfe/default', array(
                            'action' => 'listar'
                        ))?>"><i class="fa fa-list"></i> listar</a></li>
                </ul>
            </li>

        <?php endif; ?>
            <li class="header"><span>DADOS DO CONTADOR</span></li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-users"></i> <span>Clientes</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="<?php echo $this->url('cliente/default', array(
                            'action' => 'cadastrar'
                        ))?>"><i class="fa fa-user"></i> Cadastrar</a></li>
                    <li><a href="<?php echo $this->url('cliente/default', array(
                            'action' => 'listar'
                        ))?>"><i class="fa fa-list"></i> Listar</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-life-ring" aria-hidden="true"></i> <span>Suporte</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="<?php echo $this->url('suporte/default', array(
                            'action' => 'contato'
                        ))?>"><i class="fa fa-envelope-o" aria-hidden="true"></i> Contato</a></li>
                    <li><a href="<?php echo $this->url('suporte/default', array(
                            'action' => 'faq'
                        ))?>"><i class="fa fa-question" aria-hidden="true"></i> FAQ</a></li>
                </ul>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>




<?php $this->headScript()->captureStart() ?>
    $(document).ready(function () {

        $("#selecionar-cliente").change(function () {
            var stateId = $(this).val();
            if(stateId !== "") {
                // you might want to change this
                var url = "/contador/selecionar-cliente/"+stateId;
                $.getJSON( url, function( data ) {
                    location.reload();
                });
            }
        });

    });
<?php $this->headScript()->captureEnd() ?>