<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */
/** @var $entity Acl\Entity\Role */

?>
<div class="box">
    <div class="box-header">
        <!--<h3 class="box-title"></h3>-->
    </div><!-- /.box-header -->
    <div class="box-body">
        <?php echo $this->partial('partial/messages');?>
        <table id="example1" class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Papel</th>
                <th>Herança</th>
                <th></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($this->data as $entity): ?>
                <tr>
                    <td><?php echo $entity->getNome(); ?></td>
                    <td><?php echo $entity->getParent(); ?></td>
                    <td style="width: 30px;">
                        <a href="<?php echo $this->url('acl-roles/default',
                            array('action'=>'editar','id'=>$entity->getId())); ?>" class="label label-warning">
                            <i class="fa fa-pencil "></i>
                        </a>
                    </td>
                    <td style="width: 30px;">
                        <a href="<?php echo $this->url('acl-roles/default',
                            array('action'=>'deletar','id'=>$entity->getId())); ?>" title="Deletar papel" class="label label-danger">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tfoot>
        </table>
    </div><!-- /.box-body -->
</div><!-- /.box -->





